ARG BASE_IMAGE=ubuntu:22.04

FROM $BASE_IMAGE

ARG SLURM_VERSION=24.05.5
ARG DEBIAN_FRONTEND=noninteractive

# Install minimal dependencies
RUN apt-get update && \
    apt -y --no-install-recommends install \
        autoconf \
        build-essential \
        debhelper \
        devscripts \
        equivs \
        fakeroot \
        flex \
        git  \
        jq \
        libevent-dev \
        libhwloc-dev \
        libjansson-dev \
        libjson-c-dev \
        libjwt-dev \
        libjwt0 \
        liblz4-dev \
        libmunge-dev \
        libpam0g-dev \
        libpmix-dev \
        libpmix2 \
        libssl-dev \
        libtool \
        munge \
        pkg-config \
        squashfs-tools \
        wget \
        zlib1g \
        zlib1g-dev \
        zstd && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
